# .github/FUNDING.yml — Sponsor links for the "Sponsor" button on GitHub

# These are supported funding model platforms

github: [saiemgilani, sportsdataverse]
patreon: sportsdataverse
open_collective: sportsdataverse
ko_fi: saiemgilani
custom: ["https://sportsdataverse.org/donate"]
